name: CI - Java Maven

# Quando o workflow será disparado
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Baixa o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configura Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3️⃣ Cache das dependências Maven para acelerar builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Build e rodar os testes
      - name: Build and run tests
        run: mvn clean test

      # 5️⃣ Opcional: gerar relatórios ou logs
      - name: Show Maven version
        run: mvn -v

